<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <PackageId>Arc4u.AspNetCore.Versioning</PackageId>
    <Nullable>enable</Nullable>
    <NoWarn>$(NoWarn);IDE0130</NoWarn>
    <!-- MVC/ApiExplorer are not yet AOT compatible -->
    <IsAotCompatible>false</IsAotCompatible>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Asp.Versioning.Http" />
    <PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" />
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
</Project>
