<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net10.0;net11.0</TargetFrameworks>
    <PackageId>Arc4u.Threading</PackageId>
    <Description>Core threading Framework used to build application.</Description>
    <NoWarn>$(NoWarn);IDE0130</NoWarn>
  </PropertyGroup>
</Project>
