using System.Collections.Immutable;
using System.Diagnostics;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Arc4u.Dependency.Tool;

/// <summary>
/// A source generator that emits, for the compiling assembly, a <c>Register&lt;Name&gt;Types(this IServiceCollection)</c> (<c>Name</c> is the last dot-separated segment of the assembly name, cleaned into a valid identifier) extension method
/// registering every class decorated with the <c>Export</c> attribute (lifetime given by <c>Shared</c> or <c>Scoped</c>).
/// </summary>
[Generator]
public class DependencyToolGenerator : IIncrementalGenerator
{

    /// <summary>
    /// Registers the generation of the <c>Dependencies.g.cs</c> file.
    /// </summary>
    /// <param name="context">The generator initialization context.</param>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
#if DEBUG
        if (!Debugger.IsAttached)
        {
            //Debugger.Launch();
        }
#endif

        // Get class declarations having the Export attribute.
        var exportClasses = context.SyntaxProvider
                                    .CreateSyntaxProvider(
                                        predicate: static (s, _) => s is ClassDeclarationSyntax c,
                                        transform: static (ctx, _) => GetClassInfo(ctx))
                                    .Where(m => m is not null);

        var compilationAndData = context.CompilationProvider
                                        .Combine(exportClasses.Collect());

        context.RegisterSourceOutput(
                                     compilationAndData,
                                     (spc, source) =>
                                     {
                                         spc.AddSource("Dependencies.g.cs", SourceText.From(GenerateRegisterTypes(source.Left.AssemblyName, source.Right, spc.ReportDiagnostic), Encoding.UTF8));
                                     });
    }

    private string GenerateRegisterTypes(string? assemblyName, ImmutableArray<(INamedTypeSymbol Type, Location Location)?> classes, Action<Diagnostic> reportDiagnostic)
    {
        var sb = new StringBuilder();

        // Marks the emitted file as generated code so the analyzers of the consuming project skip it:
        // RegisterExtensions is partial across the files this tool emits, which rules out a
        // [GeneratedCode] attribute (it is not AllowMultiple), so the marker goes in the header.
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection.Extensions;");
        sb.AppendLine();
        sb.AppendLine("namespace Arc4u.Dependency;");
        sb.AppendLine();
        sb.AppendLine("public static partial class RegisterExtensions");
        sb.AppendLine("{");
        if (assemblyName is not null)
        {
            sb.AppendLine($"    public static void Register{ExtractName(assemblyName)}Types(this IServiceCollection services)");
            sb.AppendLine("    {");
            foreach (var _class in classes)
            {
                var (type, location) = _class!.Value;

                // Read the Export attribute information.
                var exportAttribute = type.GetAttributes().FirstOrDefault(a => a.AttributeClass?.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) == "global::Arc4u.Dependency.Attribute.ExportAttribute");
                if (exportAttribute is null)
                {
                    continue;
                }

                var isScoped = IsScoped(type);
                var isShared = IsShared(type);

                // Scoped wins, as in GenerateRegisteredTypes: the shorter lifetime cannot capture a scoped dependency in a singleton.
                if (isScoped && isShared)
                {
                    reportDiagnostic(Diagnostic.Create(DependencyDiagnostics.ConflictingLifetimes, location, type.ToDisplayString()));
                }

                var (contractName, contractType) = GetExportAttribute(exportAttribute);
                var action = isScoped ? "Scoped" : isShared ? "Singleton" : "Transient";

                if (GetGenericError(type, contractType) is { } error)
                {
                    reportDiagnostic(Diagnostic.Create(DependencyDiagnostics.GenericExportNotSupported, location, type.ToDisplayString(), error));
                    continue;
                }

                if (type.Arity > 0)
                {
                    // An open generic is registered with the non-generic overloads: typeof(IService<>), typeof(TClass<>).
                    var implementation = $"typeof({type.ConstructUnboundGenericType().ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)})";
                    var service = contractType is null ? implementation : $"typeof({contractType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)})";
                    var key = null != contractName ? $"\"{contractName}\", " : "";
                    var keyed = null != contractName ? "Keyed" : "";
                    sb.AppendLine(contractType is null && null == contractName
                        ? $"        services.Add{action}({implementation});"
                        : $"        services.Add{keyed}{action}({service}, {key}{implementation});");
                    continue;
                }

                var typeName = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                if (contractType is null)
                {
                    if (null != contractName)
                    {
                        sb.AppendLine($"        services.AddKeyed{action}<{typeName}>(\"{contractName}\");");
                    }
                    else
                    {
                        sb.AppendLine($"        services.Add{action}<{typeName}>();");
                    }
                }
                else
                {
                    if (null != contractName)
                    {
                        sb.AppendLine($"        services.AddKeyed{action}<{contractType}, {typeName}>(\"{contractName}\");");
                    }
                    else
                    {
                        sb.AppendLine($"        services.Add{action}<{contractType}, {typeName}>();");
                    }
                }
            }
            sb.AppendLine("    }");
        }
        sb.AppendLine("}");
        return sb.ToString();
    }

    // Returns why a class involving generics cannot be registered, or null when it can.
    private static string? GetGenericError(INamedTypeSymbol type, ITypeSymbol? contractType)
    {
        for (var containing = type.ContainingType; containing is not null; containing = containing.ContainingType)
        {
            if (containing.Arity > 0)
            {
                return $"it is nested in the generic type '{containing.ToDisplayString()}'";
            }
        }

        var openContract = contractType is INamedTypeSymbol { IsUnboundGenericType: true } ? (INamedTypeSymbol)contractType : null;
        if (type.Arity == 0)
        {
            return openContract is null
                ? null
                : $"the contract '{openContract.ToDisplayString()}' is an open generic type, so the class must be an open generic type with the same type parameters";
        }

        if (contractType is null)
        {
            return null;
        }

        if (openContract is null)
        {
            return $"an open generic class must be exported with an open generic contract, such as typeof({type.ConstructUnboundGenericType().ToDisplayString()}), not with '{contractType.ToDisplayString()}'";
        }

        // The container closes the class with the type arguments of the requested service, in the same order.
        var expected = openContract.OriginalDefinition.Construct(type.TypeParameters.CastArray<ITypeSymbol>().ToArray());
        var implemented = type.AllInterfaces.Cast<ITypeSymbol>().Concat(BaseTypes(type));
        if (!implemented.Any(t => SymbolEqualityComparer.Default.Equals(t, expected)))
        {
            return $"it must derive from or implement '{expected.ToDisplayString()}' to be registered as '{openContract.ToDisplayString()}'";
        }

        return null;
    }

    private static IEnumerable<ITypeSymbol> BaseTypes(INamedTypeSymbol type)
    {
        for (var baseType = type.BaseType; baseType is not null; baseType = baseType.BaseType)
        {
            yield return baseType;
        }
    }

    private string ExtractName(string assemblyName)
    {
        return ClassNameCleaner.CleanClassName(assemblyName.Split('.').Last().Trim());
    }
    // Fetch the ContractName property value from the Export attribute.
    private static (string? contractName, ITypeSymbol? contractType) GetExportAttribute(AttributeData attribute)
    {
        var constructorArguments = attribute.ConstructorArguments;
        string? contractName = null;
        ITypeSymbol? contractType = null;

        // Iterate over the constructor arguments and retrieve their values
        foreach (var constructorArgument in constructorArguments)
        {
            if (constructorArgument.Type?.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) == "string")
            {
                contractName = constructorArgument.Value?.ToString();
            }
            if (constructorArgument.Type?.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) == "global::System.Type")
            {
                contractType = constructorArgument.Value as ITypeSymbol;
            }
        }

        return (contractName, contractType);
    }

    private static bool IsScoped(INamedTypeSymbol? _class)
    {
        return _class?.GetAttributes().FirstOrDefault(a => a.AttributeClass?.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) == "global::Arc4u.Dependency.Attribute.ScopedAttribute") is not null;
    }

    private static bool IsShared(INamedTypeSymbol? _class)
    {
        return _class?.GetAttributes().FirstOrDefault(a => a.AttributeClass?.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) == "global::Arc4u.Dependency.Attribute.SharedAttribute") is not null;
    }

    private static (INamedTypeSymbol Type, Location Location)? GetClassInfo(GeneratorSyntaxContext context)
    {
        if (context.Node is not ClassDeclarationSyntax classDeclaration)
        {
            return null;
        }

        foreach (var attributeList in classDeclaration.AttributeLists)
        {
            foreach (var attribute in attributeList.Attributes)
            {
                var name = attribute.Name.ToString();
                if (name is "Export")
                {
                    var symbol = (INamedTypeSymbol?)context.SemanticModel.GetDeclaredSymbol(classDeclaration);
                    if (symbol != null)
                    {
                        return (symbol, classDeclaration.Identifier.GetLocation());
                    }
                }
            }
        }

        return null;
    }
}
